### ISSUE TITLE
Bug: Ctrl + Tab doesn't work as expected

### ISSUE THREAD

**Issue by pakosel** [FredHappyface/VSCode.OSKeybindings#5]
## Issue Details

After installing this extension Ctrl + Tab stopped working correctly - open at least 2 editors, hold Ctrl and keep pressing TAB - instead of moving from one editor to another, the shortcut stops working after first chord. Interestingly - Ctrl + Shift + Tab works as expected, i.e. it's moving in a cycle of editors when holding Ctrl + Shift and keep pressing Tab

- Operating System (OS): MacOS, Win10, Win11
- OS Version: MacOS Sonoma
- Project Version (if applicable): 1.58

**Comment by FredHappyface** [comment]
Should be fixed in the latest version for windows and linux 

- https://marketplace.visualstudio.com/items?itemName=fredhappyface.linuxkeybindings
- https://open-vsx.org/extension/fredhappyface/linuxkeybindings
- https://marketplace.visualstudio.com/items?itemName=fredhappyface.windowskeybindings
- https://open-vsx.org/extension/fredhappyface/windowskeybindings
